import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";
import Signup from '@/app/admin/signup/page'
import Login from "./login/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // first check is this firstime signup 
  // if yes redirect admin signup and signup complete redirect login page
  // if no redirect login page but in login page ceck if user has token and verify token
  // all ok 
  const signup = true
  const login = true
  return (
    <html lang="en">
    <body className={inter.className}>
      <div className="flex flex-row">
        {signup ? (
          <>
          {
            login ? (
              <> 
              <Nav />
              {children}
              </>
            ):
            (
              <Login />
            )
          }
          </>
        ) : (
          <Signup />
        )}
      </div>
    </body>
  </html>
  );
}
