export const teachers = [
    {
        id:1,
        name:'aymon',
        phoneNumber:'90000',
        gender:'male',
        religion:'islam',
        address:'Kulshi',
        classTeacher:'class8'

    },
    {
      id:1,
      name:'aymon',
      phoneNumber:'90000',
      gender:'male',
      religion:'islam',
      address:'Kulshi',
      classTeacher:'class8'
    },
   {
    id:1,
    name:'aymon',
    phoneNumber:'90000',
    gender:'male',
    religion:'islam',
    address:'Kulshi',
    classTeacher:'class8'
    },
   {
    id:1,
    name:'aymon',
    phoneNumber:'90000',
    gender:'male',
    religion:'islam',
    address:'Kulshi',
    classTeacher:'class8'
    },
    {
      id:1,
      name:'aymon',
      phoneNumber:'90000',
      gender:'male',
      religion:'islam',
      address:'Kulshi',
      classTeacher:'class8'
    }, 
    {id:1,
      name:'aymon',
      phoneNumber:'90000',
      gender:'male',
      religion:'islam',
      address:'Kulshi',
      classTeacher:'class8'
    },
    {
      id:1,
      name:'aymon',
      phoneNumber:'90000',
      gender:'male',
      religion:'islam',
      address:'Kulshi',
      classTeacher:'class8'
    },
    {
      id:1,
      name:'aymon',
      phoneNumber:'90000',
      gender:'male',
      religion:'islam',
      address:'Kulshi',
      classTeacher:'class8'
    },
  {
    id:1,
    name:'aymon',
    phoneNumber:'90000',
    gender:'male',
    religion:'islam',
    address:'Kulshi',
    classTeacher:'class8'
    },
]